// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: log.proto
// Protobuf Java Version: 4.29.3

package com.cs301.crm.protobuf;

/**
 * <pre>
 * Represents a log message that captures information about a business transaction.
 * </pre>
 *
 * Protobuf type {@code com.cs301.crm.Log}
 */
public final class Log extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:com.cs301.crm.Log)
    LogOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 29,
      /* patch= */ 3,
      /* suffix= */ "",
      Log.class.getName());
  }
  // Use Log.newBuilder() to construct.
  private Log(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private Log() {
    logId_ = "";
    transactionType_ = "";
    actorId_ = "";
    actorUsername_ = "";
    targetId_ = "";
    targetUsername_ = "";
    timestamp_ = "";
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.cs301.crm.protobuf.LogOuterClass.internal_static_com_cs301_crm_Log_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.cs301.crm.protobuf.LogOuterClass.internal_static_com_cs301_crm_Log_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.cs301.crm.protobuf.Log.class, com.cs301.crm.protobuf.Log.Builder.class);
  }

  public static final int LOG_ID_FIELD_NUMBER = 1;
  @SuppressWarnings("serial")
  private volatile java.lang.Object logId_ = "";
  /**
   * <pre>
   * Unique identifier for the log message, typically a UUID.
   * Type: string (UUID in string format)
   * Example: "123e4567-e89b-12d3-a456-426614174000"
   * </pre>
   *
   * <code>string log_id = 1;</code>
   * @return The logId.
   */
  @java.lang.Override
  public java.lang.String getLogId() {
    java.lang.Object ref = logId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      logId_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * Unique identifier for the log message, typically a UUID.
   * Type: string (UUID in string format)
   * Example: "123e4567-e89b-12d3-a456-426614174000"
   * </pre>
   *
   * <code>string log_id = 1;</code>
   * @return The bytes for logId.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getLogIdBytes() {
    java.lang.Object ref = logId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      logId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int TRANSACTION_TYPE_FIELD_NUMBER = 2;
  @SuppressWarnings("serial")
  private volatile java.lang.Object transactionType_ = "";
  /**
   * <pre>
   * The HTTP method of the transaction (e.g., "GET", "POST".).
   * Is converted to human-readable language by a Lambda.
   * Type: string (Descriptive text of the transaction)
   * </pre>
   *
   * <code>string transaction_type = 2;</code>
   * @return The transactionType.
   */
  @java.lang.Override
  public java.lang.String getTransactionType() {
    java.lang.Object ref = transactionType_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      transactionType_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * The HTTP method of the transaction (e.g., "GET", "POST".).
   * Is converted to human-readable language by a Lambda.
   * Type: string (Descriptive text of the transaction)
   * </pre>
   *
   * <code>string transaction_type = 2;</code>
   * @return The bytes for transactionType.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getTransactionTypeBytes() {
    java.lang.Object ref = transactionType_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      transactionType_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int ACTOR_ID_FIELD_NUMBER = 3;
  @SuppressWarnings("serial")
  private volatile java.lang.Object actorId_ = "";
  /**
   * <pre>
   * Unique identifier for the actor (person or system performing the action).
   * Type: string (UUID in string format)
   * Example: "123e4567-e89b-12d3-a456-426614174001"
   * </pre>
   *
   * <code>string actor_id = 3;</code>
   * @return The actorId.
   */
  @java.lang.Override
  public java.lang.String getActorId() {
    java.lang.Object ref = actorId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      actorId_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * Unique identifier for the actor (person or system performing the action).
   * Type: string (UUID in string format)
   * Example: "123e4567-e89b-12d3-a456-426614174001"
   * </pre>
   *
   * <code>string actor_id = 3;</code>
   * @return The bytes for actorId.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getActorIdBytes() {
    java.lang.Object ref = actorId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      actorId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int ACTOR_USERNAME_FIELD_NUMBER = 4;
  @SuppressWarnings("serial")
  private volatile java.lang.Object actorUsername_ = "";
  /**
   * <pre>
   * Username of the actor who performed the transaction.
   * Type: string (Username associated with the actor)
   * Example: "john_doe"
   * </pre>
   *
   * <code>string actor_username = 4;</code>
   * @return The actorUsername.
   */
  @java.lang.Override
  public java.lang.String getActorUsername() {
    java.lang.Object ref = actorUsername_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      actorUsername_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * Username of the actor who performed the transaction.
   * Type: string (Username associated with the actor)
   * Example: "john_doe"
   * </pre>
   *
   * <code>string actor_username = 4;</code>
   * @return The bytes for actorUsername.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getActorUsernameBytes() {
    java.lang.Object ref = actorUsername_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      actorUsername_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int TARGET_ID_FIELD_NUMBER = 5;
  @SuppressWarnings("serial")
  private volatile java.lang.Object targetId_ = "";
  /**
   * <pre>
   * Unique identifier for the target (person or entity affected by the transaction).
   * Type: string (UUID in string format)
   * Example: "123e4567-e89b-12d3-a456-426614174002"
   * </pre>
   *
   * <code>string target_id = 5;</code>
   * @return The targetId.
   */
  @java.lang.Override
  public java.lang.String getTargetId() {
    java.lang.Object ref = targetId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      targetId_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * Unique identifier for the target (person or entity affected by the transaction).
   * Type: string (UUID in string format)
   * Example: "123e4567-e89b-12d3-a456-426614174002"
   * </pre>
   *
   * <code>string target_id = 5;</code>
   * @return The bytes for targetId.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getTargetIdBytes() {
    java.lang.Object ref = targetId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      targetId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int TARGET_USERNAME_FIELD_NUMBER = 6;
  @SuppressWarnings("serial")
  private volatile java.lang.Object targetUsername_ = "";
  /**
   * <pre>
   * Username of the target associated with the transaction.
   * Type: string (Username associated with the target)
   * Example: "jane_smith"
   * </pre>
   *
   * <code>string target_username = 6;</code>
   * @return The targetUsername.
   */
  @java.lang.Override
  public java.lang.String getTargetUsername() {
    java.lang.Object ref = targetUsername_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      targetUsername_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * Username of the target associated with the transaction.
   * Type: string (Username associated with the target)
   * Example: "jane_smith"
   * </pre>
   *
   * <code>string target_username = 6;</code>
   * @return The bytes for targetUsername.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getTargetUsernameBytes() {
    java.lang.Object ref = targetUsername_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      targetUsername_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int TIMESTAMP_FIELD_NUMBER = 7;
  @SuppressWarnings("serial")
  private volatile java.lang.Object timestamp_ = "";
  /**
   * <pre>
   * Timestamp of when the transaction occurred, in ISO 8601 format (UTC).
   * Type: string (ISO 8601 format)
   * Example: "2021-03-11T22:04:16.000Z"
   * </pre>
   *
   * <code>string timestamp = 7;</code>
   * @return The timestamp.
   */
  @java.lang.Override
  public java.lang.String getTimestamp() {
    java.lang.Object ref = timestamp_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      timestamp_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * Timestamp of when the transaction occurred, in ISO 8601 format (UTC).
   * Type: string (ISO 8601 format)
   * Example: "2021-03-11T22:04:16.000Z"
   * </pre>
   *
   * <code>string timestamp = 7;</code>
   * @return The bytes for timestamp.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getTimestampBytes() {
    java.lang.Object ref = timestamp_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      timestamp_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(logId_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 1, logId_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(transactionType_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 2, transactionType_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(actorId_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 3, actorId_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(actorUsername_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 4, actorUsername_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(targetId_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 5, targetId_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(targetUsername_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 6, targetUsername_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(timestamp_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 7, timestamp_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(logId_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(1, logId_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(transactionType_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(2, transactionType_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(actorId_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(3, actorId_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(actorUsername_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(4, actorUsername_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(targetId_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(5, targetId_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(targetUsername_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(6, targetUsername_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(timestamp_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(7, timestamp_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.cs301.crm.protobuf.Log)) {
      return super.equals(obj);
    }
    com.cs301.crm.protobuf.Log other = (com.cs301.crm.protobuf.Log) obj;

    if (!getLogId()
        .equals(other.getLogId())) return false;
    if (!getTransactionType()
        .equals(other.getTransactionType())) return false;
    if (!getActorId()
        .equals(other.getActorId())) return false;
    if (!getActorUsername()
        .equals(other.getActorUsername())) return false;
    if (!getTargetId()
        .equals(other.getTargetId())) return false;
    if (!getTargetUsername()
        .equals(other.getTargetUsername())) return false;
    if (!getTimestamp()
        .equals(other.getTimestamp())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + LOG_ID_FIELD_NUMBER;
    hash = (53 * hash) + getLogId().hashCode();
    hash = (37 * hash) + TRANSACTION_TYPE_FIELD_NUMBER;
    hash = (53 * hash) + getTransactionType().hashCode();
    hash = (37 * hash) + ACTOR_ID_FIELD_NUMBER;
    hash = (53 * hash) + getActorId().hashCode();
    hash = (37 * hash) + ACTOR_USERNAME_FIELD_NUMBER;
    hash = (53 * hash) + getActorUsername().hashCode();
    hash = (37 * hash) + TARGET_ID_FIELD_NUMBER;
    hash = (53 * hash) + getTargetId().hashCode();
    hash = (37 * hash) + TARGET_USERNAME_FIELD_NUMBER;
    hash = (53 * hash) + getTargetUsername().hashCode();
    hash = (37 * hash) + TIMESTAMP_FIELD_NUMBER;
    hash = (53 * hash) + getTimestamp().hashCode();
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.cs301.crm.protobuf.Log parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.cs301.crm.protobuf.Log parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.cs301.crm.protobuf.Log parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.cs301.crm.protobuf.Log parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.cs301.crm.protobuf.Log parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.cs301.crm.protobuf.Log parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.cs301.crm.protobuf.Log parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.cs301.crm.protobuf.Log parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static com.cs301.crm.protobuf.Log parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static com.cs301.crm.protobuf.Log parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.cs301.crm.protobuf.Log parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.cs301.crm.protobuf.Log parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.cs301.crm.protobuf.Log prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * Represents a log message that captures information about a business transaction.
   * </pre>
   *
   * Protobuf type {@code com.cs301.crm.Log}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:com.cs301.crm.Log)
      com.cs301.crm.protobuf.LogOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.cs301.crm.protobuf.LogOuterClass.internal_static_com_cs301_crm_Log_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.cs301.crm.protobuf.LogOuterClass.internal_static_com_cs301_crm_Log_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.cs301.crm.protobuf.Log.class, com.cs301.crm.protobuf.Log.Builder.class);
    }

    // Construct using com.cs301.crm.protobuf.Log.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      logId_ = "";
      transactionType_ = "";
      actorId_ = "";
      actorUsername_ = "";
      targetId_ = "";
      targetUsername_ = "";
      timestamp_ = "";
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.cs301.crm.protobuf.LogOuterClass.internal_static_com_cs301_crm_Log_descriptor;
    }

    @java.lang.Override
    public com.cs301.crm.protobuf.Log getDefaultInstanceForType() {
      return com.cs301.crm.protobuf.Log.getDefaultInstance();
    }

    @java.lang.Override
    public com.cs301.crm.protobuf.Log build() {
      com.cs301.crm.protobuf.Log result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.cs301.crm.protobuf.Log buildPartial() {
      com.cs301.crm.protobuf.Log result = new com.cs301.crm.protobuf.Log(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(com.cs301.crm.protobuf.Log result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.logId_ = logId_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.transactionType_ = transactionType_;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.actorId_ = actorId_;
      }
      if (((from_bitField0_ & 0x00000008) != 0)) {
        result.actorUsername_ = actorUsername_;
      }
      if (((from_bitField0_ & 0x00000010) != 0)) {
        result.targetId_ = targetId_;
      }
      if (((from_bitField0_ & 0x00000020) != 0)) {
        result.targetUsername_ = targetUsername_;
      }
      if (((from_bitField0_ & 0x00000040) != 0)) {
        result.timestamp_ = timestamp_;
      }
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.cs301.crm.protobuf.Log) {
        return mergeFrom((com.cs301.crm.protobuf.Log)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.cs301.crm.protobuf.Log other) {
      if (other == com.cs301.crm.protobuf.Log.getDefaultInstance()) return this;
      if (!other.getLogId().isEmpty()) {
        logId_ = other.logId_;
        bitField0_ |= 0x00000001;
        onChanged();
      }
      if (!other.getTransactionType().isEmpty()) {
        transactionType_ = other.transactionType_;
        bitField0_ |= 0x00000002;
        onChanged();
      }
      if (!other.getActorId().isEmpty()) {
        actorId_ = other.actorId_;
        bitField0_ |= 0x00000004;
        onChanged();
      }
      if (!other.getActorUsername().isEmpty()) {
        actorUsername_ = other.actorUsername_;
        bitField0_ |= 0x00000008;
        onChanged();
      }
      if (!other.getTargetId().isEmpty()) {
        targetId_ = other.targetId_;
        bitField0_ |= 0x00000010;
        onChanged();
      }
      if (!other.getTargetUsername().isEmpty()) {
        targetUsername_ = other.targetUsername_;
        bitField0_ |= 0x00000020;
        onChanged();
      }
      if (!other.getTimestamp().isEmpty()) {
        timestamp_ = other.timestamp_;
        bitField0_ |= 0x00000040;
        onChanged();
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              logId_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            case 18: {
              transactionType_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000002;
              break;
            } // case 18
            case 26: {
              actorId_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000004;
              break;
            } // case 26
            case 34: {
              actorUsername_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000008;
              break;
            } // case 34
            case 42: {
              targetId_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000010;
              break;
            } // case 42
            case 50: {
              targetUsername_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000020;
              break;
            } // case 50
            case 58: {
              timestamp_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000040;
              break;
            } // case 58
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private java.lang.Object logId_ = "";
    /**
     * <pre>
     * Unique identifier for the log message, typically a UUID.
     * Type: string (UUID in string format)
     * Example: "123e4567-e89b-12d3-a456-426614174000"
     * </pre>
     *
     * <code>string log_id = 1;</code>
     * @return The logId.
     */
    public java.lang.String getLogId() {
      java.lang.Object ref = logId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        logId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * Unique identifier for the log message, typically a UUID.
     * Type: string (UUID in string format)
     * Example: "123e4567-e89b-12d3-a456-426614174000"
     * </pre>
     *
     * <code>string log_id = 1;</code>
     * @return The bytes for logId.
     */
    public com.google.protobuf.ByteString
        getLogIdBytes() {
      java.lang.Object ref = logId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        logId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * Unique identifier for the log message, typically a UUID.
     * Type: string (UUID in string format)
     * Example: "123e4567-e89b-12d3-a456-426614174000"
     * </pre>
     *
     * <code>string log_id = 1;</code>
     * @param value The logId to set.
     * @return This builder for chaining.
     */
    public Builder setLogId(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      logId_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Unique identifier for the log message, typically a UUID.
     * Type: string (UUID in string format)
     * Example: "123e4567-e89b-12d3-a456-426614174000"
     * </pre>
     *
     * <code>string log_id = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearLogId() {
      logId_ = getDefaultInstance().getLogId();
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Unique identifier for the log message, typically a UUID.
     * Type: string (UUID in string format)
     * Example: "123e4567-e89b-12d3-a456-426614174000"
     * </pre>
     *
     * <code>string log_id = 1;</code>
     * @param value The bytes for logId to set.
     * @return This builder for chaining.
     */
    public Builder setLogIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      logId_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }

    private java.lang.Object transactionType_ = "";
    /**
     * <pre>
     * The HTTP method of the transaction (e.g., "GET", "POST".).
     * Is converted to human-readable language by a Lambda.
     * Type: string (Descriptive text of the transaction)
     * </pre>
     *
     * <code>string transaction_type = 2;</code>
     * @return The transactionType.
     */
    public java.lang.String getTransactionType() {
      java.lang.Object ref = transactionType_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        transactionType_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * The HTTP method of the transaction (e.g., "GET", "POST".).
     * Is converted to human-readable language by a Lambda.
     * Type: string (Descriptive text of the transaction)
     * </pre>
     *
     * <code>string transaction_type = 2;</code>
     * @return The bytes for transactionType.
     */
    public com.google.protobuf.ByteString
        getTransactionTypeBytes() {
      java.lang.Object ref = transactionType_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        transactionType_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * The HTTP method of the transaction (e.g., "GET", "POST".).
     * Is converted to human-readable language by a Lambda.
     * Type: string (Descriptive text of the transaction)
     * </pre>
     *
     * <code>string transaction_type = 2;</code>
     * @param value The transactionType to set.
     * @return This builder for chaining.
     */
    public Builder setTransactionType(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      transactionType_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * The HTTP method of the transaction (e.g., "GET", "POST".).
     * Is converted to human-readable language by a Lambda.
     * Type: string (Descriptive text of the transaction)
     * </pre>
     *
     * <code>string transaction_type = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearTransactionType() {
      transactionType_ = getDefaultInstance().getTransactionType();
      bitField0_ = (bitField0_ & ~0x00000002);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * The HTTP method of the transaction (e.g., "GET", "POST".).
     * Is converted to human-readable language by a Lambda.
     * Type: string (Descriptive text of the transaction)
     * </pre>
     *
     * <code>string transaction_type = 2;</code>
     * @param value The bytes for transactionType to set.
     * @return This builder for chaining.
     */
    public Builder setTransactionTypeBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      transactionType_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }

    private java.lang.Object actorId_ = "";
    /**
     * <pre>
     * Unique identifier for the actor (person or system performing the action).
     * Type: string (UUID in string format)
     * Example: "123e4567-e89b-12d3-a456-426614174001"
     * </pre>
     *
     * <code>string actor_id = 3;</code>
     * @return The actorId.
     */
    public java.lang.String getActorId() {
      java.lang.Object ref = actorId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        actorId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * Unique identifier for the actor (person or system performing the action).
     * Type: string (UUID in string format)
     * Example: "123e4567-e89b-12d3-a456-426614174001"
     * </pre>
     *
     * <code>string actor_id = 3;</code>
     * @return The bytes for actorId.
     */
    public com.google.protobuf.ByteString
        getActorIdBytes() {
      java.lang.Object ref = actorId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        actorId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * Unique identifier for the actor (person or system performing the action).
     * Type: string (UUID in string format)
     * Example: "123e4567-e89b-12d3-a456-426614174001"
     * </pre>
     *
     * <code>string actor_id = 3;</code>
     * @param value The actorId to set.
     * @return This builder for chaining.
     */
    public Builder setActorId(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      actorId_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Unique identifier for the actor (person or system performing the action).
     * Type: string (UUID in string format)
     * Example: "123e4567-e89b-12d3-a456-426614174001"
     * </pre>
     *
     * <code>string actor_id = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearActorId() {
      actorId_ = getDefaultInstance().getActorId();
      bitField0_ = (bitField0_ & ~0x00000004);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Unique identifier for the actor (person or system performing the action).
     * Type: string (UUID in string format)
     * Example: "123e4567-e89b-12d3-a456-426614174001"
     * </pre>
     *
     * <code>string actor_id = 3;</code>
     * @param value The bytes for actorId to set.
     * @return This builder for chaining.
     */
    public Builder setActorIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      actorId_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }

    private java.lang.Object actorUsername_ = "";
    /**
     * <pre>
     * Username of the actor who performed the transaction.
     * Type: string (Username associated with the actor)
     * Example: "john_doe"
     * </pre>
     *
     * <code>string actor_username = 4;</code>
     * @return The actorUsername.
     */
    public java.lang.String getActorUsername() {
      java.lang.Object ref = actorUsername_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        actorUsername_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * Username of the actor who performed the transaction.
     * Type: string (Username associated with the actor)
     * Example: "john_doe"
     * </pre>
     *
     * <code>string actor_username = 4;</code>
     * @return The bytes for actorUsername.
     */
    public com.google.protobuf.ByteString
        getActorUsernameBytes() {
      java.lang.Object ref = actorUsername_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        actorUsername_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * Username of the actor who performed the transaction.
     * Type: string (Username associated with the actor)
     * Example: "john_doe"
     * </pre>
     *
     * <code>string actor_username = 4;</code>
     * @param value The actorUsername to set.
     * @return This builder for chaining.
     */
    public Builder setActorUsername(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      actorUsername_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Username of the actor who performed the transaction.
     * Type: string (Username associated with the actor)
     * Example: "john_doe"
     * </pre>
     *
     * <code>string actor_username = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearActorUsername() {
      actorUsername_ = getDefaultInstance().getActorUsername();
      bitField0_ = (bitField0_ & ~0x00000008);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Username of the actor who performed the transaction.
     * Type: string (Username associated with the actor)
     * Example: "john_doe"
     * </pre>
     *
     * <code>string actor_username = 4;</code>
     * @param value The bytes for actorUsername to set.
     * @return This builder for chaining.
     */
    public Builder setActorUsernameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      actorUsername_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }

    private java.lang.Object targetId_ = "";
    /**
     * <pre>
     * Unique identifier for the target (person or entity affected by the transaction).
     * Type: string (UUID in string format)
     * Example: "123e4567-e89b-12d3-a456-426614174002"
     * </pre>
     *
     * <code>string target_id = 5;</code>
     * @return The targetId.
     */
    public java.lang.String getTargetId() {
      java.lang.Object ref = targetId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        targetId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * Unique identifier for the target (person or entity affected by the transaction).
     * Type: string (UUID in string format)
     * Example: "123e4567-e89b-12d3-a456-426614174002"
     * </pre>
     *
     * <code>string target_id = 5;</code>
     * @return The bytes for targetId.
     */
    public com.google.protobuf.ByteString
        getTargetIdBytes() {
      java.lang.Object ref = targetId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        targetId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * Unique identifier for the target (person or entity affected by the transaction).
     * Type: string (UUID in string format)
     * Example: "123e4567-e89b-12d3-a456-426614174002"
     * </pre>
     *
     * <code>string target_id = 5;</code>
     * @param value The targetId to set.
     * @return This builder for chaining.
     */
    public Builder setTargetId(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      targetId_ = value;
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Unique identifier for the target (person or entity affected by the transaction).
     * Type: string (UUID in string format)
     * Example: "123e4567-e89b-12d3-a456-426614174002"
     * </pre>
     *
     * <code>string target_id = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearTargetId() {
      targetId_ = getDefaultInstance().getTargetId();
      bitField0_ = (bitField0_ & ~0x00000010);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Unique identifier for the target (person or entity affected by the transaction).
     * Type: string (UUID in string format)
     * Example: "123e4567-e89b-12d3-a456-426614174002"
     * </pre>
     *
     * <code>string target_id = 5;</code>
     * @param value The bytes for targetId to set.
     * @return This builder for chaining.
     */
    public Builder setTargetIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      targetId_ = value;
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }

    private java.lang.Object targetUsername_ = "";
    /**
     * <pre>
     * Username of the target associated with the transaction.
     * Type: string (Username associated with the target)
     * Example: "jane_smith"
     * </pre>
     *
     * <code>string target_username = 6;</code>
     * @return The targetUsername.
     */
    public java.lang.String getTargetUsername() {
      java.lang.Object ref = targetUsername_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        targetUsername_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * Username of the target associated with the transaction.
     * Type: string (Username associated with the target)
     * Example: "jane_smith"
     * </pre>
     *
     * <code>string target_username = 6;</code>
     * @return The bytes for targetUsername.
     */
    public com.google.protobuf.ByteString
        getTargetUsernameBytes() {
      java.lang.Object ref = targetUsername_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        targetUsername_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * Username of the target associated with the transaction.
     * Type: string (Username associated with the target)
     * Example: "jane_smith"
     * </pre>
     *
     * <code>string target_username = 6;</code>
     * @param value The targetUsername to set.
     * @return This builder for chaining.
     */
    public Builder setTargetUsername(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      targetUsername_ = value;
      bitField0_ |= 0x00000020;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Username of the target associated with the transaction.
     * Type: string (Username associated with the target)
     * Example: "jane_smith"
     * </pre>
     *
     * <code>string target_username = 6;</code>
     * @return This builder for chaining.
     */
    public Builder clearTargetUsername() {
      targetUsername_ = getDefaultInstance().getTargetUsername();
      bitField0_ = (bitField0_ & ~0x00000020);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Username of the target associated with the transaction.
     * Type: string (Username associated with the target)
     * Example: "jane_smith"
     * </pre>
     *
     * <code>string target_username = 6;</code>
     * @param value The bytes for targetUsername to set.
     * @return This builder for chaining.
     */
    public Builder setTargetUsernameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      targetUsername_ = value;
      bitField0_ |= 0x00000020;
      onChanged();
      return this;
    }

    private java.lang.Object timestamp_ = "";
    /**
     * <pre>
     * Timestamp of when the transaction occurred, in ISO 8601 format (UTC).
     * Type: string (ISO 8601 format)
     * Example: "2021-03-11T22:04:16.000Z"
     * </pre>
     *
     * <code>string timestamp = 7;</code>
     * @return The timestamp.
     */
    public java.lang.String getTimestamp() {
      java.lang.Object ref = timestamp_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        timestamp_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * Timestamp of when the transaction occurred, in ISO 8601 format (UTC).
     * Type: string (ISO 8601 format)
     * Example: "2021-03-11T22:04:16.000Z"
     * </pre>
     *
     * <code>string timestamp = 7;</code>
     * @return The bytes for timestamp.
     */
    public com.google.protobuf.ByteString
        getTimestampBytes() {
      java.lang.Object ref = timestamp_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        timestamp_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * Timestamp of when the transaction occurred, in ISO 8601 format (UTC).
     * Type: string (ISO 8601 format)
     * Example: "2021-03-11T22:04:16.000Z"
     * </pre>
     *
     * <code>string timestamp = 7;</code>
     * @param value The timestamp to set.
     * @return This builder for chaining.
     */
    public Builder setTimestamp(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      timestamp_ = value;
      bitField0_ |= 0x00000040;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Timestamp of when the transaction occurred, in ISO 8601 format (UTC).
     * Type: string (ISO 8601 format)
     * Example: "2021-03-11T22:04:16.000Z"
     * </pre>
     *
     * <code>string timestamp = 7;</code>
     * @return This builder for chaining.
     */
    public Builder clearTimestamp() {
      timestamp_ = getDefaultInstance().getTimestamp();
      bitField0_ = (bitField0_ & ~0x00000040);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Timestamp of when the transaction occurred, in ISO 8601 format (UTC).
     * Type: string (ISO 8601 format)
     * Example: "2021-03-11T22:04:16.000Z"
     * </pre>
     *
     * <code>string timestamp = 7;</code>
     * @param value The bytes for timestamp to set.
     * @return This builder for chaining.
     */
    public Builder setTimestampBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      timestamp_ = value;
      bitField0_ |= 0x00000040;
      onChanged();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:com.cs301.crm.Log)
  }

  // @@protoc_insertion_point(class_scope:com.cs301.crm.Log)
  private static final com.cs301.crm.protobuf.Log DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.cs301.crm.protobuf.Log();
  }

  public static com.cs301.crm.protobuf.Log getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<Log>
      PARSER = new com.google.protobuf.AbstractParser<Log>() {
    @java.lang.Override
    public Log parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<Log> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<Log> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.cs301.crm.protobuf.Log getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

