// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: log.proto
// Protobuf Java Version: 4.29.3

package com.cs301.crm.protobuf;

public final class LogOuterClass {
  private LogOuterClass() {}
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 29,
      /* patch= */ 3,
      /* suffix= */ "",
      LogOuterClass.class.getName());
  }
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_cs301_crm_Log_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_cs301_crm_Log_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\tlog.proto\022\rcom.cs301.crm\"\230\001\n\003Log\022\016\n\006lo" +
      "g_id\030\001 \001(\t\022\030\n\020transaction_type\030\002 \001(\t\022\020\n\010" +
      "actor_id\030\003 \001(\t\022\026\n\016actor_username\030\004 \001(\t\022\021" +
      "\n\ttarget_id\030\005 \001(\t\022\027\n\017target_username\030\006 \001" +
      "(\t\022\021\n\ttimestamp\030\007 \001(\tB\032\n\026com.cs301.crm.p" +
      "rotobufP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_com_cs301_crm_Log_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_cs301_crm_Log_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_com_cs301_crm_Log_descriptor,
        new java.lang.String[] { "LogId", "TransactionType", "ActorId", "ActorUsername", "TargetId", "TargetUsername", "Timestamp", });
    descriptor.resolveAllFeaturesImmutable();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
