// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: log.proto
// Protobuf Java Version: 4.29.3

package com.cs301.crm.protobuf;

public interface LogOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.cs301.crm.Log)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * Unique identifier for the log message, typically a UUID.
   * Type: string (UUID in string format)
   * Example: "123e4567-e89b-12d3-a456-426614174000"
   * </pre>
   *
   * <code>string log_id = 1;</code>
   * @return The logId.
   */
  java.lang.String getLogId();
  /**
   * <pre>
   * Unique identifier for the log message, typically a UUID.
   * Type: string (UUID in string format)
   * Example: "123e4567-e89b-12d3-a456-426614174000"
   * </pre>
   *
   * <code>string log_id = 1;</code>
   * @return The bytes for logId.
   */
  com.google.protobuf.ByteString
      getLogIdBytes();

  /**
   * <pre>
   * The HTTP method of the transaction (e.g., "GET", "POST".).
   * Is converted to human-readable language by a Lambda.
   * Type: string (Descriptive text of the transaction)
   * </pre>
   *
   * <code>string transaction_type = 2;</code>
   * @return The transactionType.
   */
  java.lang.String getTransactionType();
  /**
   * <pre>
   * The HTTP method of the transaction (e.g., "GET", "POST".).
   * Is converted to human-readable language by a Lambda.
   * Type: string (Descriptive text of the transaction)
   * </pre>
   *
   * <code>string transaction_type = 2;</code>
   * @return The bytes for transactionType.
   */
  com.google.protobuf.ByteString
      getTransactionTypeBytes();

  /**
   * <pre>
   * Unique identifier for the actor (person or system performing the action).
   * Type: string (UUID in string format)
   * Example: "123e4567-e89b-12d3-a456-426614174001"
   * </pre>
   *
   * <code>string actor_id = 3;</code>
   * @return The actorId.
   */
  java.lang.String getActorId();
  /**
   * <pre>
   * Unique identifier for the actor (person or system performing the action).
   * Type: string (UUID in string format)
   * Example: "123e4567-e89b-12d3-a456-426614174001"
   * </pre>
   *
   * <code>string actor_id = 3;</code>
   * @return The bytes for actorId.
   */
  com.google.protobuf.ByteString
      getActorIdBytes();

  /**
   * <pre>
   * Username of the actor who performed the transaction.
   * Type: string (Username associated with the actor)
   * Example: "john_doe"
   * </pre>
   *
   * <code>string actor_username = 4;</code>
   * @return The actorUsername.
   */
  java.lang.String getActorUsername();
  /**
   * <pre>
   * Username of the actor who performed the transaction.
   * Type: string (Username associated with the actor)
   * Example: "john_doe"
   * </pre>
   *
   * <code>string actor_username = 4;</code>
   * @return The bytes for actorUsername.
   */
  com.google.protobuf.ByteString
      getActorUsernameBytes();

  /**
   * <pre>
   * Unique identifier for the target (person or entity affected by the transaction).
   * Type: string (UUID in string format)
   * Example: "123e4567-e89b-12d3-a456-426614174002"
   * </pre>
   *
   * <code>string target_id = 5;</code>
   * @return The targetId.
   */
  java.lang.String getTargetId();
  /**
   * <pre>
   * Unique identifier for the target (person or entity affected by the transaction).
   * Type: string (UUID in string format)
   * Example: "123e4567-e89b-12d3-a456-426614174002"
   * </pre>
   *
   * <code>string target_id = 5;</code>
   * @return The bytes for targetId.
   */
  com.google.protobuf.ByteString
      getTargetIdBytes();

  /**
   * <pre>
   * Username of the target associated with the transaction.
   * Type: string (Username associated with the target)
   * Example: "jane_smith"
   * </pre>
   *
   * <code>string target_username = 6;</code>
   * @return The targetUsername.
   */
  java.lang.String getTargetUsername();
  /**
   * <pre>
   * Username of the target associated with the transaction.
   * Type: string (Username associated with the target)
   * Example: "jane_smith"
   * </pre>
   *
   * <code>string target_username = 6;</code>
   * @return The bytes for targetUsername.
   */
  com.google.protobuf.ByteString
      getTargetUsernameBytes();

  /**
   * <pre>
   * Timestamp of when the transaction occurred, in ISO 8601 format (UTC).
   * Type: string (ISO 8601 format)
   * Example: "2021-03-11T22:04:16.000Z"
   * </pre>
   *
   * <code>string timestamp = 7;</code>
   * @return The timestamp.
   */
  java.lang.String getTimestamp();
  /**
   * <pre>
   * Timestamp of when the transaction occurred, in ISO 8601 format (UTC).
   * Type: string (ISO 8601 format)
   * Example: "2021-03-11T22:04:16.000Z"
   * </pre>
   *
   * <code>string timestamp = 7;</code>
   * @return The bytes for timestamp.
   */
  com.google.protobuf.ByteString
      getTimestampBytes();
}
