server:
  port: 8081

spring:
  application:
    name: user-service
  datasource:
      url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/user-db}
      driverClassName: org.postgresql.Driver
      username: ${SPRING_DATASOURCE_USERNAME:postgres}
      password: ${SPRING_DATASOURCE_PASSWORD:password}
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: ${SPRING_JPA_DDL:create-drop}
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}

kafka:
  topic:
    log: ${KAFKA_LOG_TOPIC:logs}
  schema:
    registry: ${KAFKA_REGISTRY:scrooge-bank-registry}
    protobuf:
      log: ${KAFKA_PROTOBUF_LOG:log.proto}

cors:
  origin: ${CORS_ORIGIN:http://localhost:9000}

cookie:
  httpsEnabled: ${HTTPS_ENABLED:false}

jwt:
  id: ${JWT_KEY_ID:6f976ce0-4aad-47d7-a141-b7d40e44ea16}
  public:
    key: ${JWT_PUBLIC_KEY:MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAtGnaj7iZohusudAuqSI/FOjeuPiroTHgvULsP3s2i/RzDa2fKExo/+PeoViFa1nk3ieSxFTvZ+2tahMsm/30xN6KSG7F/RX5DrV9Rf5HHumPeGl8HiJrWTnuViKD1FtxYa2p9l9Yx7PjxqvAGtD0wJ6Gejyp2wJtj/daEz4iWYA2mMTesANsQ5uEM1RWr2cs57LfirYUf3v3HsbVyreYZstoJkrwKusiuv/75wvse374xQL8EZiRyklppgd2c152uC65UKDP3+lfSpyO+IeWDHXesqsO6HtciDgIKVz4aYbdi1Ly67NXXKSVQYgZocQjhNum9aidtR86r1CBvO80BQIDAQAB}
  refresh:
    duration: ${JWT_REFRESH_DURATION:72000}
  access:
    duration: ${JWT_EXPIRATION_TIME:240}
